"""Generates a Python client module from a Contract Document — the two output shapes of
contract-document.md §5.3-§5.4:

- :func:`generate_service_client` — one client **class** per service, one method per request topic
  (§5.2's topic include-list projection: ``requests[]`` filtered, ``events``/``components``
  unnarrowed).
- :func:`generate_topic_client` — one self-contained client **module**, generated for exactly one
  topic, scoped to only that topic's reachable schema closure (§5.3).

Both emit a single, self-contained Python module: the ``@dataclass`` types the client's method(s)
use, the client class itself, a ``REQUIRED_TOPICS`` constant (the ``RequiredTopics``-equivalent,
parity checklist row 8), a ``CONTRACT_HASH`` constant (§6), and a ``create_*_client(sender)``
factory function (parity checklist row 9 — see module docstring in ``cli.py`` for why a factory
function rather than a DI container integration).

Generated code's only runtime dependency is ``benzene.core.clients.MessageSender`` and
``benzene.results.Result`` (§5.4) — no transport, no HTTP client, nothing else.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from . import types
from .contract_hash import compute as compute_contract_hash
from .document import ContractDocument, RequestResponse, to_raw_document
from .naming import class_name, default_method_name, topic_identifier
from .schema_closure import reachable_schemas
from .topic_scope import TopicScopeOptions, apply_topic_scope

_HEADER = (
    '"""Generated by benzene-codegen-client from a Contract Document. DO NOT EDIT BY HAND —\n'
    "regenerate instead (see docs/codegen-client.md's build-integration note).\n"
    '"""\n\n'
    "from __future__ import annotations\n\n"
    "from dataclasses import dataclass, field\n"
    "from typing import Any, Union, cast\n\n"
    "from benzene.core.clients import MessageSender\n"
    "from benzene.results import Result\n"
)


def _topological_schema_order(schemas: dict[str, Any]) -> list[str]:
    """Emission order for ``schemas``: a dependency (``allOf`` base, union alias member) is always
    emitted before the schema that references it (see :func:`types.dependency_names`)."""
    order: list[str] = []
    emitted: set[str] = set()

    def visit(name: str, stack: set[str]) -> None:
        if name in emitted or name not in schemas or name in stack:
            return
        stack = stack | {name}
        for dep in types.dependency_names(schemas[name]):
            if dep in schemas:
                visit(dep, stack)
        emitted.add(name)
        order.append(name)

    for name in schemas:
        visit(name, set())
    return order


def _render_schemas(schemas: dict[str, Any]) -> str:
    if not schemas:
        return ""
    order = _topological_schema_order(schemas)
    blocks = [types.build_schema_source(name, schemas[name], schemas) for name in order]
    return "\n".join(blocks) + "\n"


def _render_method(request: RequestResponse, catalogue: dict[str, Any], method_name: str) -> str:
    request_type = types.get_type_name(request.request, catalogue)
    response_type = types.get_type_name(request.response, catalogue)
    return (
        f"    async def {method_name}(\n"
        f"        self, request: {request_type}, headers: dict[str, str] | None = None\n"
        f"    ) -> Result[{response_type}]:\n"
        f'        """Calls topic {request.topic!r}."""\n'
        f"        result = await self._sender.send_message({request.topic!r}, request, headers)\n"
        f"        return cast(Result[{response_type}], result)\n"
    )


@dataclass(frozen=True)
class GeneratedClient:
    """A generated client module plus the metadata a caller (the CLI, a test) needs about it."""

    source: str
    contract_hash: str
    required_topics: tuple[str, ...]
    class_name: str
    factory_name: str


def generate_service_client(
    document: ContractDocument,
    *,
    service_name: str,
    topics: tuple[str, ...] | None = None,
    include_reserved: bool = False,
) -> GeneratedClient:
    """Service-level client: one class, one method per in-scope request topic.

    ``components``/``events`` are left unnarrowed (§5.2) — every schema in the source document is
    emitted, whether or not an in-scope method's request/response reaches it, matching the .NET
    reference's ``MessageClientSdkBuilder`` (which types every method against
    ``scopedDocument.Components.Schemas`` — TopicScope narrows ``requests[]`` only).
    """
    scoped = apply_topic_scope(
        document, TopicScopeOptions(topics=topics, include_reserved=include_reserved)
    )

    raw = to_raw_document(scoped)
    contract_hash = compute_contract_hash(raw, topic_scoped=False)

    cls_name = f"{class_name(service_name)}Client"
    module_ident = topic_identifier(service_name) or "service"
    factory_name = f"create_{module_ident}_client"

    parts: list[str] = [_HEADER]
    schemas_source = _render_schemas(scoped.schemas)
    if schemas_source:
        parts.append(schemas_source)

    required_topics = tuple(r.topic for r in scoped.requests)
    parts.append(f"REQUIRED_TOPICS: tuple[str, ...] = {required_topics!r}\n")
    parts.append(f"CONTRACT_HASH = {contract_hash!r}\n")

    class_lines = [f"class {cls_name}:", f'    """Typed client for the {service_name!r} service."""', ""]
    class_lines.append("    def __init__(self, sender: MessageSender) -> None:")
    class_lines.append("        self._sender = sender")
    class_lines.append("")

    used_names: set[str] = set()
    for request in scoped.requests:
        method_name = default_method_name(request.topic)
        if method_name in used_names:
            method_name = f"{method_name}_{topic_identifier(request.topic)}"
        used_names.add(method_name)
        class_lines.append(_render_method(request, scoped.schemas, method_name))

    if not scoped.requests:
        class_lines.append("    pass")

    parts.append("\n".join(class_lines) + "\n")

    parts.append(
        f"def {factory_name}(sender: MessageSender) -> {cls_name}:\n"
        f'    """Builds a {cls_name} over ``sender``. Import this module (or scan its package) to\n'
        "    register it — this port's handler/client discovery is import-driven, not reflective.\n"
        '    """\n'
        f"    return {cls_name}(sender)\n"
    )

    source = "\n".join(parts)
    return GeneratedClient(
        source=source,
        contract_hash=contract_hash,
        required_topics=required_topics,
        class_name=cls_name,
        factory_name=factory_name,
    )


class TopicNotFoundError(ValueError):
    def __init__(self, topic: str, valid_topics: list[str]) -> None:
        self.topic = topic
        self.valid_topics = sorted(valid_topics)
        super().__init__(
            f"Topic {topic!r} is not present in the document. "
            f"Valid topics: {', '.join(self.valid_topics)}."
        )


def generate_topic_client(document: ContractDocument, *, topic: str) -> GeneratedClient:
    """Topic-scoped client (§5.3): one self-contained module for exactly one topic.

    Naming a topic explicitly always admits it (contract-document.md §5.2), reserved or not — this
    mirrors the .NET reference's ``AtomicClientSdkBuilder``, whose inner options set
    ``IncludeReservedTopics = true`` for exactly this reason.
    """
    request = document.find_request(topic)
    if request is None:
        raise TopicNotFoundError(topic, [r.topic for r in document.requests])

    closure = reachable_schemas(document.schemas, request.request, request.response)
    projected = ContractDocument(
        openapi=document.openapi,
        info=document.info,
        requests=(request,),
        events=(),
        schemas=closure,
        message_endpoint=document.message_endpoint,
        transports=document.transports,
    )

    raw = to_raw_document(projected)
    contract_hash = compute_contract_hash(raw, topic_scoped=True)

    ident = topic_identifier(topic)
    cls_name = f"{class_name(ident)}Client"
    factory_name = f"create_{ident}_client"
    method_name = default_method_name(topic)

    parts: list[str] = [_HEADER]
    schemas_source = _render_schemas(closure)
    if schemas_source:
        parts.append(schemas_source)

    parts.append(f"REQUIRED_TOPICS: tuple[str, ...] = ({topic!r},)\n")
    parts.append(f"CONTRACT_HASH = {contract_hash!r}\n")

    class_lines = [
        f"class {cls_name}:",
        f'    """Self-contained client for topic {topic!r} only."""',
        "",
        "    def __init__(self, sender: MessageSender) -> None:",
        "        self._sender = sender",
        "",
        _render_method(request, closure, method_name),
    ]
    parts.append("\n".join(class_lines) + "\n")

    parts.append(
        f"def {factory_name}(sender: MessageSender) -> {cls_name}:\n"
        f'    """Builds a {cls_name} over ``sender``."""\n'
        f"    return {cls_name}(sender)\n"
    )

    source = "\n".join(parts)
    return GeneratedClient(
        source=source,
        contract_hash=contract_hash,
        required_topics=(topic,),
        class_name=cls_name,
        factory_name=factory_name,
    )
